name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  
  push: {branches: ["main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_limit: 2                            
          plugin_tweets_user: aurosvr
